apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: redis-cluster-3master
spec:
  version: 5.0.3-v1
  mode: Cluster
  # Added
  configSource:
    configMap:
      name: rd-custom-config
  cluster:
    master: 3
    replicas: 1
  # storageType: Ephemeral
  storageType: Durable
  storage:
    resources:
      requests:
        storage: 1Gi
    storageClassName: "standard"
    accessModes:
      - ReadWriteOnce
  # terminationPolicy: WipeOut
  terminationPolicy: Pause
  updateStrategy:
    type: RollingUpdate

